version: "3"
services:
  spring-boot-app:
    image: sxxdxh2/game:latest
    container_name: gamecommunity
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=${spring.datasource.url}
      - username=${username}
      - password=${password}
      - gmail=${gmail}
      - mail_password=${mail_password}
      - access-key=${access-key}
      - secret-key=${secret-key}
      - jwt.secret.key=${jwt.secret.key}
      - admin.token=${admin.token}
      - kakao.rest_api_key=${kakao.rest_api_key}
      - kakao.redirect_uri=${kakao.redirect_uri}
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
