spring:
  datasource:
    url: jdbc:mysql://localhost:${port}/${db_name}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
    #auth-code-expiration-millis: 600000

cloud:
  aws:
    credentials:
      access-key: ${access-key}
      secret-key: ${secret-key}
    s3:
      bucket: game-post-image
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  secret:
    key: ${jwt.secret.key}

admin:
  token: ${admin.token}

kakao:
  rest_api_key: ${kakao.rest_api_key}
  redirect_uri: ${kakao.redirect_uri}
