name: GameCommunity Deploy

on:
  pull_request:
    branches: [ "dev" ]
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, label-development]
    steps:
      - name: Docker-compose run
        run: |
          docker compose down
          docker compose pull
          docker compose up -d
