name: GameCommunity Deploy

on:
  workflow_run:
    workflows: ["GameCommunity"]
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, label-development]
    steps:
      - name: Docker-compose run
        run: |
          docker compose down
          docker compose pull
          docker compose up -d
