name: GameCommunity Deploy

on:
  pull_request:
    branches: [ "main" ]
    types: [closed]

jobs:
  deploy:
    runs-on: [self-hosted, label-development]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker-compose run
        run: |
          docker compose down
          docker compose pull
          docker compose up -d
