# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: GameCommunity

# PR이 닫힐 때 깃허브 액션 돌아감
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
    types: [closed]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          distribution: 'adopt'
          java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 기존 build한 파일이 존재한다면 캐싱하여 build 속도를 높일 수 있음
    - name: cache
      uses: actions/cache@v2
      with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew build


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1


    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to DockerHub
      uses: docker/build-push-action@v4
      with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_TAG }}

  deploy:
    needs: build-docker-image
    name: Deploy
    runs-on: [ self-hosted, label-development ]
    steps:
      - name: Docker run
        run: |
          sudo docker stop gamecommunity && docker rm gamecommunity && docker rmi ${{ secrets.DOCKERHUB_TAG }}
          sudo docker run -d -p 80:8080 ${{ secrets.PROD_ENV }} --name gamecommunity ${{ secrets.DOCKERHUB_TAG }}
